POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjVlNDg1YzE5ODg5MWIwMTZjYzQ2ZGIyYyIsImlhdCI6MTU4MTgwMTkyM30.WY-fErVZfRVUlXpok2IO9L-PcufhPzoobklKnw878DI

{
    "title": "Dis",
    "author": "Mama",
    "url": "new"
}